tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/app.pem
        keyFile: /etc/traefik/certs/app-key.pem
  certificates:
    - certFile: /etc/traefik/certs/app.pem
      keyFile: /etc/traefik/certs/app-key.pem
