# Traefik configuration file
entryPoints:
  websecure:
    address: ":443"
  web:
    address: ":80"
providers:
  docker:
    endpoint: unix:///var/run/docker.sock
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true
api:
  dashboard: true
serversTransport:
  insecureSkipVerify: true
