CREATE TABLE alert_rules (
  id SERIAL PRIMARY KEY,
  content VARCHAR(255) NOT NULL,
  alert_id INTEGER NOT NULL REFERENCES alerts(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL
);
